In [1]:
import tensorflow as tf

2022-06-27 14:22:22.186820: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-27 14:22:22.186841: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__ # vendo se o tensorflow esta instalado de forma correta

'2.9.1'

# Criando tensors

In [4]:
text = tf.Variable("hello world", tf.string) #variavel padrao string, possui rank 0 por ser um escalar (apenas um valor)
tf.rank(text)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [5]:
text_array = tf.Variable(["hello", "world"], tf.string) #array, possui rank 1 por ser um array
tf.rank(text_array)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
text_matrix = tf.Variable([["hello", "world"], ["it's", "tf"]], tf.string) #matriz, possui rank 2 por ter duas dimensoes (altura e largura)
tf.rank(text_matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Número de elementos

In [8]:
matrix = tf.Variable([["hello", "world"], ["it's", "tf"], ["testing", "this"]], tf.string)
matrix.shape #isso mostra o numero de dimensoes e o numero de elementos em cada dimensao

TensorShape([3, 2])

# Criando tensores com valores 1

In [21]:
scalar = tf.ones(1)
vector = tf.ones(2)
matrix = tf.ones(3)
rank_3_tensor = tf.ones([1,2,3])
print(f"escalar: {scalar}")
print(f"vetor: {vector}")
print(f"matriz: {matrix}")
print(f"tensor rank 3: {rank_3_tensor}")

escalar: [1.]
vetor: [1. 1.]
matriz: [1. 1. 1.]
tensor rank 3: [[[1. 1. 1.]
  [1. 1. 1.]]]


# Mudando o formato dos tensors

In [23]:
tensor = tf.ones([1,2,3])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [35]:
tf.reshape(tensor, [3,2,1]) # modifica o shape do tensor criado a cima

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [36]:
tf.reshape(tensor, [3,-1]) # o -1 diz para a funcao encontrar o numero de dimensoes necessaria para ter 3 valores (nesse caso) em cada

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [37]:
tf.reshape(tensor, [1, -1])

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[1., 1., 1., 1., 1., 1.]], dtype=float32)>

# tipos de Tensors

* Variable
* Constant
* Placeholder (feito para a versão 1 do tensorflow)
* SparseTensor

apenas o `Variable` é mutavel

In [39]:
variable  = tf.Variable("test", tf.string)
variable

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'test'>

In [42]:
constant = tf.constant("test", tf.string)
constant

<tf.Tensor: shape=(), dtype=string, numpy=b'test'>

In [5]:
tf.compat.v1.disable_eager_execution()

placeholder = tf.compat.v1.placeholder(tf.int16, shape=(2, 3), name="tensorTest") # o placeholder sera uma maneira de criar uma template de um tensor que mais para frente sera usado para inserir valores no formato previsto
operation = placeholder * 13 # operacao que sera feita com os dados para colcoar dentro do placeholder

with tf.compat.v1.Session() as session: #usar sessions nao e mais necessario na v2 do tensorflow, mas como estamos usando uma feature da v1 entao foi necessario
    operation_res = session.run(operation, feed_dict={placeholder: [[1, 1, 1], [2, 2, 2]]}) #faz as operacoes para cada um desses valores e coloca eles no plcaholder
    print("resultado: " + str(operation_res))


resultado: [[13 13 13]
 [26 26 26]]


In [63]:
"""
cria um tensor como todos os valores zero e coloca nesses indices o valor corespondente que voce deixou em values
"""
tf.sparse.SparseTensor(indices=((0, 0), (1,0), (1,1)), values=(1, 2, 3), dense_shape=(2, 3))
  

# Criando um tensor com zeros

In [68]:
tf.zeros([2,3]) # semelhante a funcao ones, no entanto essa cria um tensor com zeros

<tf.Tensor 'zeros_3:0' shape=(2, 3) dtype=float32>

# Alguns testes

In [2]:
tensor_a = tf.ones([2, 5, 3, 10])
print(tensor_a)

tf.Tensor(
[[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.

2022-06-27 14:22:23.337282: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-27 14:22:23.337576: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-27 14:22:23.337624: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-06-27 14:22:23.337667: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-06-27 14:22:23.337708: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [10]:
from numpy import prod
#2 * 5 * 3 * 10 --> 10 * 3 * 10 --> 30 * 10 --> 300
new_shape = prod(list(tensor_a.shape))

tf.reshape(tensor_a, [new_shape])


<tf.Tensor: shape=(300,), dtype=float32, numpy=
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1